import { CardsLibrary } from './cards.library';
import { IDeck } from '../@shared/rest-shared/entities';

export class DecksLibrary {

  static readonly decks: IDeck[] = [
    {
      id: `hunter`,
      type: 'destiny',
      name: {
        en: ``,
        fr: `Chasseur`,
      },
      description: {
        en: ``,
        fr: ``,
      },
      cards: [
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('replacement'),
        CardsLibrary.find('replacement'),
        CardsLibrary.find('thunder'),
        CardsLibrary.find('thunder'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('gargoyle'),
        CardsLibrary.find('gargoyle'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('soul-of-a-sacrified-hunter'),
        CardsLibrary.find('soul-of-a-sacrified-hunter'),
        CardsLibrary.find('hunter'),
      ],
    },
    {
      id: `conjurer`,
      type: 'destiny',
      name: {
        en: ``,
        fr: `Illusionniste`,
      },
      description: {
        en: ``,
        fr: ``,
      },
      cards: [
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),

        CardsLibrary.find('conjurer'),
      ],
    },
    {
      id: `summoner`,
      type: 'destiny',
      name: {
        en: ``,
        fr: `Invocateur`,
      },
      description: {
        en: ``,
        fr: ``,
      },
      cards: [
        CardsLibrary.find('ruin'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('summoner'),
      ],
    },
    {
      id: `sorcerer`,
      type: 'destiny',
      name: {
        en: ``,
        fr: `Prestidigitateur`,
      },
      description: {
        en: ``,
        fr: ``,
      },
      cards: [
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('sorcerer'),
      ],
    },
  ];

  static find(id: string): IDeck|undefined {
    return this.decks.find(e => e.id === id);
  }

}
