import { CardsLibrary } from './cards.library';
import { IDeck } from '@thefirstspine/types-game';

export class DecksLibrary {

  static readonly decks: IDeck[] = [
    {
      id: `hunter`,
      type: 'destiny',
      name: {
        en: `Hunter`,
        fr: `Chasseur`,
      },
      description: {
        en: `The Hunter has all the assets to track down the wizards of Exodia and is not specialized in any field. Using the weapons of his opponents is his specialty.`,
        fr: `Le Chasseur dispose de tous les atouts pour traquer les sorciers d'Exodia et n'est spécialisé dans aucun domaine. Utiliser les armes de ses adversaires est sa spécialité.`,
      },
      cards: [
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('replacement'),
        CardsLibrary.find('replacement'),
        CardsLibrary.find('thunder'),
        CardsLibrary.find('thunder'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('gargoyle'),
        CardsLibrary.find('gargoyle'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('soul-of-a-sacrified-hunter'),
        CardsLibrary.find('soul-of-a-sacrified-hunter'),
        CardsLibrary.find('hunter'),
      ],
    },
    {
      id: `conjurer`,
      type: 'destiny',
      name: {
        en: `Conjurer`,
        fr: `Illusionniste`,
      },
      description: {
        en: `The Conjurer can bring up great artifacts just by thought to generate steadfast defenses. He's specialized in artifacts and defense.`,
        fr: `L'Illusionniste peut faire apparaître de grands artefacts rien que par la pensée pour engendrer des défenses inébranlables. Il est spécialisé dans les artéfacts et la défense.`,
      },
      cards: [
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('the-wall'),
        CardsLibrary.find('the-wall'),
        CardsLibrary.find('shadows-banner'),
        CardsLibrary.find('shadows-banner'),
        CardsLibrary.find('monstrous-portal'),
        CardsLibrary.find('monstrous-portal'),
        CardsLibrary.find('insanes-run'),
        CardsLibrary.find('insanes-run'),
        CardsLibrary.find('insanes-run'),
        CardsLibrary.find('insanes-run'),
        CardsLibrary.find('growing-oak'),
        CardsLibrary.find('growing-oak'),
        CardsLibrary.find('conjurer'),
      ],
    },
    {
      id: `summoner`,
      type: 'destiny',
      name: {
        en: `Summoner`,
        fr: `Invocateur`,
      },
      description: {
        en: `The summoner can materialize creatures straight out of the adversaries' nightmares. He's specialized in creatures and attack.`,
        fr: `L'invocateur peut matérialiser des créatures sorties tout droit des cauchemars de ses adversaires. Il est spécialisé dans les créatures et l'attaque.`,
      },
      cards: [
        CardsLibrary.find('ruin'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('paladin-of-the-ninth-desert'),
        CardsLibrary.find('paladin-of-the-ninth-desert'),
        CardsLibrary.find('deadly-viper'),
        CardsLibrary.find('deadly-viper'),
        CardsLibrary.find('volkha'),
        CardsLibrary.find('insanes-echo'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('jester'),
        CardsLibrary.find('summoner'),
      ],
    },
    {
      id: `sorcerer`,
      type: 'destiny',
      name: {
        en: `Sorcerer`,
        fr: `Prestidigitateur`,
      },
      description: {
        en: `Neither summoner nor illusionist, the Sorcerer has powerful spells to thwart the strategies of his opponents. He's specialized in spells.`,
        fr: `Ni invocateur, ni illusionniste, le Prestidigitateur dispose de puissants sortilèges pour déjouer les stratégies de ses adversaires. Il est spécialisé dans les sortilèges.`,
      },
      cards: [
        CardsLibrary.find('banshee'),
        CardsLibrary.find('banshee'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('the-fox'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('veneniagora'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('smoky-totem'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('the-tower'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('barbers'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('putrefaction'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('ruin'),
        CardsLibrary.find('heal'),
        CardsLibrary.find('reconstruct'),
        CardsLibrary.find('achieve'),
        CardsLibrary.find('achieve'),
        CardsLibrary.find('achieve'),
        CardsLibrary.find('ether'),
        CardsLibrary.find('ether'),
        CardsLibrary.find('ether'),
        CardsLibrary.find('ether'),
        CardsLibrary.find('alter-the-fate'),
        CardsLibrary.find('alter-the-fate'),
        CardsLibrary.find('alter-the-fate'),
        CardsLibrary.find('fire'),
        CardsLibrary.find('fire'),
        CardsLibrary.find('sorcerer'),
      ],
    },
    {
      id: `healer`,
      type: 'origin',
      name: {
        en: `Healer`,
        fr: `Guérisseur`,
      },
      description: {
        en: `The healer has a healing spell and a whole range of defenses.`,
        fr: `Le guérisseur dispose de sort de soins et de toute une panoplie défensive.`,
      },
      cards: [
        CardsLibrary.find('cure'),
        CardsLibrary.find('cure'),
        CardsLibrary.find('guardian'),
        CardsLibrary.find('guardian'),
        CardsLibrary.find('caduceus'),
        CardsLibrary.find('caduceus'),
      ],
    },
    {
      id: `architect`,
      type: 'origin',
      name: {
        en: `Architect`,
        fr: `Architecte`,
      },
      description: {
        en: `The architect can modify the playing field at will.`,
        fr: `L'architecte peut modifier le terrain de jeu à sa guise.`,
      },
      cards: [
        CardsLibrary.find('the-void'),
        CardsLibrary.find('the-void'),
        CardsLibrary.find('jellyfish'),
        CardsLibrary.find('jellyfish'),
        CardsLibrary.find('pocket-volcano'),
        CardsLibrary.find('pocket-volcano'),
      ],
    },
    {
      id: `priest`,
      type: 'origin',
      name: {
        en: `Priest`,
        fr: `Prêtre`,
      },
      description: {
        en: `The Priest knows the pangs of pain and uses it for his own ends.`,
        fr: `Le Prêtre connaît les affres de la douleur et s'en sert à ses propres fins.`,
      },
      cards: [
        CardsLibrary.find('torturer'),
        CardsLibrary.find('torturer'),
        CardsLibrary.find('chimera'),
        CardsLibrary.find('chimera'),
        CardsLibrary.find('pain'),
        CardsLibrary.find('pain'),
      ],
    },
    {
      id: `blacksmith`,
      type: 'origin',
      name: {
        en: `Blacksmith`,
        fr: `Forgeron`,
      },
      description: {
        en: `The blacksmith can make his cards almost invincible by forging a defense of steel.`,
        fr: `Le forgeron peut rendre ses cartes quasiment invincibles en lui forgeant une défense d’acier.`,
      },
      cards: [
        CardsLibrary.find('anvil-of-xiarmha'),
        CardsLibrary.find('anvil-of-xiarmha'),
        CardsLibrary.find('flesh-hammer'),
        CardsLibrary.find('flesh-hammer'),
        CardsLibrary.find('reinforcement'),
        CardsLibrary.find('reinforcement'),
      ],
    },
  ];

  static find(id: string): IDeck|undefined {
    return this.decks.find(e => e.id === id);
  }

}
